#!/usr/bin/env python3

'''Check a non-zero return code is considered a failure.'''

import drake
import utils


class TouchShellCommand(drake.ShellCommand):

  def execute(self):
    for target in self.targets():
      target.path().touch()
    return super().execute()


with utils.Drake() as d:
  source = drake.touch('source')
  target = drake.node('target')
  b = TouchShellCommand([source], [target], ['false'])
  try:
    import sys
    target.build()

  except drake.Builder.Failed as e:
    assert e.builder is b
  else:
    raise Exception('build should have failed')
