#!/usr/bin/env python3

'''Check the build chain stops when a builder fails.'''

import drake
import stat

from utils import *

def configure(foo: bool):
  assert foo is False

print(__file__)

class CommandBuilder(drake.Builder):

  def __init__(self, exe, target):
    super().__init__([exe], [target])
    self.__exe = exe
    self.__target = target

  def execute(self):
    self.cmd(pretty = 'Execute {}'.format(self.__exe),
             cmd = ['./{}'.format(self.__exe)],
             env = {'BAZ': 'quux'}, throw = True)
    self.__target.path().touch()
    return True

with Drake() as d:
  os.environ.update({'FOO': 'bar'})
  os.environ.update({'BAZ': 'nope'})
  exe = drake.node('test')
  drake.WriteBuilder(
    '''#!/bin/sh -e
test $FOO = bar
test $BAZ = quux''',
    exe,
    permissions = stat.S_IXUSR)
  r = drake.Runner(exe,
                   env = {'BAZ': 'quux'})
  r.status.build()
  beacon = drake.node('beacon')
  r = CommandBuilder(exe, beacon)
  beacon.build()
