#!/usr/bin/env python3
# -*- python -*-

import drake

with drake.Drake():
  source = drake.node('drake.node')
  source.path().remove()
  target = drake.copy(source, 'output')
  target.path().remove()
  try:
    target.build()
  except drake.NoBuilder:
    pass
