#!/usr/bin/env python3

import os.path
import socket
import subprocess
import sys

p = subprocess.Popen([sys.argv[1]], stdout = subprocess.PIPE)
line = next(p.stdout)
port = int(line.decode().strip().split(' ')[3])
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('localhost', port))
message = b'Hello world!\n'
s.send(message)
data = s.recv(1024)
assert message == data
