//
// ---------- header ----------------------------------------------------------
//
// project       infinit
//
// license       infinit (c)
//
// file          /home/mycure/infinit/etoile/components/Voucher.hh
//
// created       julien quintard   [mon feb 16 21:13:00 2009]
// updated       julien quintard   [mon jul 27 08:32:13 2009]
//

#ifndef ETOILE_COMPONENTS_VOUCHER_HH
#define ETOILE_COMPONENTS_VOUCHER_HH

//
// ---------- includes --------------------------------------------------------
//

#include <elle/Elle.hh>

#include <ostream>

namespace etoile
{
  namespace components
  {

//
// ---------- class -----------------------------------------------------------
//

    ///
    /// a voucher represents a certificate, generated by a delegate,
    /// proving that a consumer had the right the perform an operation
    /// at the time it has been carried out.
    ///
    class Voucher:
      public Entity,
      public Dumpable, public Archivable
    {
    public:
      //
      // constants
      //
      static const String		Class;

      //
      // constructors & destructors
      //
      Voucher()
      {
	Voucher::New(*this);
      }

      ~Voucher()
      {
	Voucher::Delete(*this);
      }

      //
      // methods
      //
      // XXX Status		Generate(PublicKey&, ...);

      //
      // operators
      //
      static Status	New(Voucher&);
      static Status	Delete(Voucher&);

      Voucher&		operator=(const Voucher&);
      Boolean		operator==(const Voucher&);
      Boolean		operator!=(const Voucher&);

      //
      // interfaces
      //

      // dumpable
      Status		Dump(const Natural32 = 0);

      // archivable
      Status		Serialize(Archive&) const;
      Status		Extract(Archive&);

      //
      // attributes
      //
      PublicKey		consumer;
      Signature		signature;
    };

  }
}

#endif
