#!/bin/sh

INFINIT_SOURCE_DIR=$(git rev-parse --show-toplevel)
INFINIT_BUILD_DIR=${INFINIT_SOURCE_DIR}/build

ELLE_LOG_COMPONENTS="infinit.*"
ELLE_LOG_COMPONENTS="${ELLE_LOG_COMPONENTS},reactor.network.*"
ELLE_LOG_COMPONENTS="${ELLE_LOG_COMPONENTS},elle.HTTPClient"

DISTCC_HOSTS="infinit.im"

env INFINIT_BUILD_DIR=${INFINIT_BUILD_DIR} \
    INFINIT_SOURCE_DIR=${INFINIT_SOURCE_DIR} \
    ELLE_LOG_COMPONENTS="${ELLE_LOG_COMPONENTS}" \
    ELLE_LOG_LEVEL=DEBUG \
    PYTHONPATH=${INFINIT_BUILD_DIR}/lib/python \
    RPROMPT="infinit env" \
    PATH="${INFINIT_SOURCE_DIR}/scripts/:${PATH}" \
    DISTCC_HOSTS="${DISTCC_HOSTS}" \
    zsh 
