# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/charlesguillot/Projects/Infinit/infinit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/charlesguillot/Projects/Infinit/infinit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/charlesguillot/Projects/Infinit/infinit/CMakeFiles /Users/charlesguillot/Projects/Infinit/infinit/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/charlesguillot/Projects/Infinit/infinit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 8infinit

# Build rule for target.
8infinit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 8infinit
.PHONY : 8infinit

# fast build rule for target.
8infinit/fast:
	$(MAKE) -f CMakeFiles/8infinit.dir/build.make CMakeFiles/8infinit.dir/build
.PHONY : 8infinit/fast

#=============================================================================
# Target rules for targets named dependencies

# Build rule for target.
dependencies: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dependencies
.PHONY : dependencies

# fast build rule for target.
dependencies/fast:
	$(MAKE) -f CMakeFiles/dependencies.dir/build.make CMakeFiles/dependencies.dir/build
.PHONY : dependencies/fast

#=============================================================================
# Target rules for targets named infinit

# Build rule for target.
infinit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 infinit
.PHONY : infinit

# fast build rule for target.
infinit/fast:
	$(MAKE) -f CMakeFiles/infinit.dir/build.make CMakeFiles/infinit.dir/build
.PHONY : infinit/fast

#=============================================================================
# Target rules for targets named comet

# Build rule for target.
comet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comet
.PHONY : comet

# fast build rule for target.
comet/fast:
	$(MAKE) -f comet/CMakeFiles/comet.dir/build.make comet/CMakeFiles/comet.dir/build
.PHONY : comet/fast

#=============================================================================
# Target rules for targets named elle

# Build rule for target.
elle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 elle
.PHONY : elle

# fast build rule for target.
elle/fast:
	$(MAKE) -f elle/CMakeFiles/elle.dir/build.make elle/CMakeFiles/elle.dir/build
.PHONY : elle/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f common/CMakeFiles/common.dir/build.make common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named nucleus

# Build rule for target.
nucleus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nucleus
.PHONY : nucleus

# fast build rule for target.
nucleus/fast:
	$(MAKE) -f nucleus/CMakeFiles/nucleus.dir/build.make nucleus/CMakeFiles/nucleus.dir/build
.PHONY : nucleus/fast

#=============================================================================
# Target rules for targets named protocol

# Build rule for target.
protocol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protocol
.PHONY : protocol

# fast build rule for target.
protocol/fast:
	$(MAKE) -f protocol/CMakeFiles/protocol.dir/build.make protocol/CMakeFiles/protocol.dir/build
.PHONY : protocol/fast

#=============================================================================
# Target rules for targets named etoile

# Build rule for target.
etoile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 etoile
.PHONY : etoile

# fast build rule for target.
etoile/fast:
	$(MAKE) -f etoile/CMakeFiles/etoile.dir/build.make etoile/CMakeFiles/etoile.dir/build
.PHONY : etoile/fast

#=============================================================================
# Target rules for targets named agent

# Build rule for target.
agent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 agent
.PHONY : agent

# fast build rule for target.
agent/fast:
	$(MAKE) -f agent/CMakeFiles/agent.dir/build.make agent/CMakeFiles/agent.dir/build
.PHONY : agent/fast

#=============================================================================
# Target rules for targets named lune

# Build rule for target.
lune: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lune
.PHONY : lune

# fast build rule for target.
lune/fast:
	$(MAKE) -f lune/CMakeFiles/lune.dir/build.make lune/CMakeFiles/lune.dir/build
.PHONY : lune/fast

#=============================================================================
# Target rules for targets named horizon

# Build rule for target.
horizon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 horizon
.PHONY : horizon

# fast build rule for target.
horizon/fast:
	$(MAKE) -f horizon/CMakeFiles/horizon.dir/build.make horizon/CMakeFiles/horizon.dir/build
.PHONY : horizon/fast

#=============================================================================
# Target rules for targets named macosx

# Build rule for target.
macosx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 macosx
.PHONY : macosx

# fast build rule for target.
macosx/fast:
	$(MAKE) -f horizon/macosx/CMakeFiles/macosx.dir/build.make horizon/macosx/CMakeFiles/macosx.dir/build
.PHONY : macosx/fast

#=============================================================================
# Target rules for targets named hole

# Build rule for target.
hole: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hole
.PHONY : hole

# fast build rule for target.
hole/fast:
	$(MAKE) -f hole/CMakeFiles/hole.dir/build.make hole/CMakeFiles/hole.dir/build
.PHONY : hole/fast

#=============================================================================
# Target rules for targets named 8access

# Build rule for target.
8access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 8access
.PHONY : 8access

# fast build rule for target.
8access/fast:
	$(MAKE) -f satellites/access/CMakeFiles/8access.dir/build.make satellites/access/CMakeFiles/8access.dir/build
.PHONY : 8access/fast

#=============================================================================
# Target rules for targets named 8authority

# Build rule for target.
8authority: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 8authority
.PHONY : 8authority

# fast build rule for target.
8authority/fast:
	$(MAKE) -f satellites/authority/CMakeFiles/8authority.dir/build.make satellites/authority/CMakeFiles/8authority.dir/build
.PHONY : 8authority/fast

#=============================================================================
# Target rules for targets named 8dictionary

# Build rule for target.
8dictionary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 8dictionary
.PHONY : 8dictionary

# fast build rule for target.
8dictionary/fast:
	$(MAKE) -f satellites/dictionary/CMakeFiles/8dictionary.dir/build.make satellites/dictionary/CMakeFiles/8dictionary.dir/build
.PHONY : 8dictionary/fast

#=============================================================================
# Target rules for targets named 8group

# Build rule for target.
8group: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 8group
.PHONY : 8group

# fast build rule for target.
8group/fast:
	$(MAKE) -f satellites/group/CMakeFiles/8group.dir/build.make satellites/group/CMakeFiles/8group.dir/build
.PHONY : 8group/fast

#=============================================================================
# Target rules for targets named 8network

# Build rule for target.
8network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 8network
.PHONY : 8network

# fast build rule for target.
8network/fast:
	$(MAKE) -f satellites/network/CMakeFiles/8network.dir/build.make satellites/network/CMakeFiles/8network.dir/build
.PHONY : 8network/fast

#=============================================================================
# Target rules for targets named 8passport

# Build rule for target.
8passport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 8passport
.PHONY : 8passport

# fast build rule for target.
8passport/fast:
	$(MAKE) -f satellites/passport/CMakeFiles/8passport.dir/build.make satellites/passport/CMakeFiles/8passport.dir/build
.PHONY : 8passport/fast

#=============================================================================
# Target rules for targets named 8setup

# Build rule for target.
8setup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 8setup
.PHONY : 8setup

# fast build rule for target.
8setup/fast:
	$(MAKE) -f satellites/setup/CMakeFiles/8setup.dir/build.make satellites/setup/CMakeFiles/8setup.dir/build
.PHONY : 8setup/fast

#=============================================================================
# Target rules for targets named 8user

# Build rule for target.
8user: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 8user
.PHONY : 8user

# fast build rule for target.
8user/fast:
	$(MAKE) -f satellites/user/CMakeFiles/8user.dir/build.make satellites/user/CMakeFiles/8user.dir/build
.PHONY : 8user/fast

#=============================================================================
# Target rules for targets named 8watchdog

# Build rule for target.
8watchdog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 8watchdog
.PHONY : 8watchdog

# fast build rule for target.
8watchdog/fast:
	$(MAKE) -f plasma/watchdog/CMakeFiles/8watchdog.dir/build.make plasma/watchdog/CMakeFiles/8watchdog.dir/build
.PHONY : 8watchdog/fast

#=============================================================================
# Target rules for targets named metal

# Build rule for target.
metal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 metal
.PHONY : metal

# fast build rule for target.
metal/fast:
	$(MAKE) -f plasma/meta/CMakeFiles/metal.dir/build.make plasma/meta/CMakeFiles/metal.dir/build
.PHONY : metal/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f tests/CMakeFiles/test.dir/build.make tests/CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_testing_tests

# Build rule for target.
test_testing_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_testing_tests
.PHONY : test_testing_tests

# fast build rule for target.
test_testing_tests/fast:
	$(MAKE) -f tests/CMakeFiles/test_testing_tests.dir/build.make tests/CMakeFiles/test_testing_tests.dir/build
.PHONY : test_testing_tests/fast

#=============================================================================
# Target rules for targets named test_log

# Build rule for target.
test_log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_log
.PHONY : test_log

# fast build rule for target.
test_log/fast:
	$(MAKE) -f tests/unittest/elle/CMakeFiles/test_log.dir/build.make tests/unittest/elle/CMakeFiles/test_log.dir/build
.PHONY : test_log/fast

#=============================================================================
# Target rules for targets named test_print

# Build rule for target.
test_print: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_print
.PHONY : test_print

# fast build rule for target.
test_print/fast:
	$(MAKE) -f tests/unittest/elle/CMakeFiles/test_print.dir/build.make tests/unittest/elle/CMakeFiles/test_print.dir/build
.PHONY : test_print/fast

#=============================================================================
# Target rules for targets named test_ec_PrivateKey

# Build rule for target.
test_ec_PrivateKey: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ec_PrivateKey
.PHONY : test_ec_PrivateKey

# fast build rule for target.
test_ec_PrivateKey/fast:
	$(MAKE) -f tests/unittest/elle/cryptography/CMakeFiles/test_ec_PrivateKey.dir/build.make tests/unittest/elle/cryptography/CMakeFiles/test_ec_PrivateKey.dir/build
.PHONY : test_ec_PrivateKey/fast

#=============================================================================
# Target rules for targets named test_ec_SecretKey

# Build rule for target.
test_ec_SecretKey: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ec_SecretKey
.PHONY : test_ec_SecretKey

# fast build rule for target.
test_ec_SecretKey/fast:
	$(MAKE) -f tests/unittest/elle/cryptography/CMakeFiles/test_ec_SecretKey.dir/build.make tests/unittest/elle/cryptography/CMakeFiles/test_ec_SecretKey.dir/build
.PHONY : test_ec_SecretKey/fast

#=============================================================================
# Target rules for targets named test_ec_all

# Build rule for target.
test_ec_all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ec_all
.PHONY : test_ec_all

# fast build rule for target.
test_ec_all/fast:
	$(MAKE) -f tests/unittest/elle/cryptography/CMakeFiles/test_ec_all.dir/build.make tests/unittest/elle/cryptography/CMakeFiles/test_ec_all.dir/build
.PHONY : test_ec_all/fast

#=============================================================================
# Target rules for targets named test_Section

# Build rule for target.
test_Section: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Section
.PHONY : test_Section

# fast build rule for target.
test_Section/fast:
	$(MAKE) -f tests/unittest/elle/format/ini/CMakeFiles/test_Section.dir/build.make tests/unittest/elle/format/ini/CMakeFiles/test_Section.dir/build
.PHONY : test_Section/fast

#=============================================================================
# Target rules for targets named test_Array

# Build rule for target.
test_Array: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Array
.PHONY : test_Array

# fast build rule for target.
test_Array/fast:
	$(MAKE) -f tests/unittest/elle/format/json/CMakeFiles/test_Array.dir/build.make tests/unittest/elle/format/json/CMakeFiles/test_Array.dir/build
.PHONY : test_Array/fast

#=============================================================================
# Target rules for targets named test_Bool

# Build rule for target.
test_Bool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Bool
.PHONY : test_Bool

# fast build rule for target.
test_Bool/fast:
	$(MAKE) -f tests/unittest/elle/format/json/CMakeFiles/test_Bool.dir/build.make tests/unittest/elle/format/json/CMakeFiles/test_Bool.dir/build
.PHONY : test_Bool/fast

#=============================================================================
# Target rules for targets named test_Dictionary

# Build rule for target.
test_Dictionary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Dictionary
.PHONY : test_Dictionary

# fast build rule for target.
test_Dictionary/fast:
	$(MAKE) -f tests/unittest/elle/format/json/CMakeFiles/test_Dictionary.dir/build.make tests/unittest/elle/format/json/CMakeFiles/test_Dictionary.dir/build
.PHONY : test_Dictionary/fast

#=============================================================================
# Target rules for targets named test_Float

# Build rule for target.
test_Float: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Float
.PHONY : test_Float

# fast build rule for target.
test_Float/fast:
	$(MAKE) -f tests/unittest/elle/format/json/CMakeFiles/test_Float.dir/build.make tests/unittest/elle/format/json/CMakeFiles/test_Float.dir/build
.PHONY : test_Float/fast

#=============================================================================
# Target rules for targets named test_Integer

# Build rule for target.
test_Integer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Integer
.PHONY : test_Integer

# fast build rule for target.
test_Integer/fast:
	$(MAKE) -f tests/unittest/elle/format/json/CMakeFiles/test_Integer.dir/build.make tests/unittest/elle/format/json/CMakeFiles/test_Integer.dir/build
.PHONY : test_Integer/fast

#=============================================================================
# Target rules for targets named test_Null

# Build rule for target.
test_Null: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Null
.PHONY : test_Null

# fast build rule for target.
test_Null/fast:
	$(MAKE) -f tests/unittest/elle/format/json/CMakeFiles/test_Null.dir/build.make tests/unittest/elle/format/json/CMakeFiles/test_Null.dir/build
.PHONY : test_Null/fast

#=============================================================================
# Target rules for targets named test_String

# Build rule for target.
test_String: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_String
.PHONY : test_String

# fast build rule for target.
test_String/fast:
	$(MAKE) -f tests/unittest/elle/format/json/CMakeFiles/test_String.dir/build.make tests/unittest/elle/format/json/CMakeFiles/test_String.dir/build
.PHONY : test_String/fast

#=============================================================================
# Target rules for targets named test_Locus

# Build rule for target.
test_Locus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Locus
.PHONY : test_Locus

# fast build rule for target.
test_Locus/fast:
	$(MAKE) -f tests/unittest/elle/network/CMakeFiles/test_Locus.dir/build.make tests/unittest/elle/network/CMakeFiles/test_Locus.dir/build
.PHONY : test_Locus/fast

#=============================================================================
# Target rules for targets named test_Path

# Build rule for target.
test_Path: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Path
.PHONY : test_Path

# fast build rule for target.
test_Path/fast:
	$(MAKE) -f tests/unittest/elle/io/CMakeFiles/test_Path.dir/build.make tests/unittest/elle/io/CMakeFiles/test_Path.dir/build
.PHONY : test_Path/fast

#=============================================================================
# Target rules for targets named test_Base64Archive

# Build rule for target.
test_Base64Archive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Base64Archive
.PHONY : test_Base64Archive

# fast build rule for target.
test_Base64Archive/fast:
	$(MAKE) -f tests/unittest/elle/serialize/CMakeFiles/test_Base64Archive.dir/build.make tests/unittest/elle/serialize/CMakeFiles/test_Base64Archive.dir/build
.PHONY : test_Base64Archive/fast

#=============================================================================
# Target rules for targets named test_BinaryArchive

# Build rule for target.
test_BinaryArchive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_BinaryArchive
.PHONY : test_BinaryArchive

# fast build rule for target.
test_BinaryArchive/fast:
	$(MAKE) -f tests/unittest/elle/serialize/CMakeFiles/test_BinaryArchive.dir/build.make tests/unittest/elle/serialize/CMakeFiles/test_BinaryArchive.dir/build
.PHONY : test_BinaryArchive/fast

#=============================================================================
# Target rules for targets named test_BufferArchive

# Build rule for target.
test_BufferArchive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_BufferArchive
.PHONY : test_BufferArchive

# fast build rule for target.
test_BufferArchive/fast:
	$(MAKE) -f tests/unittest/elle/serialize/CMakeFiles/test_BufferArchive.dir/build.make tests/unittest/elle/serialize/CMakeFiles/test_BufferArchive.dir/build
.PHONY : test_BufferArchive/fast

#=============================================================================
# Target rules for targets named test_JSONArchive

# Build rule for target.
test_JSONArchive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_JSONArchive
.PHONY : test_JSONArchive

# fast build rule for target.
test_JSONArchive/fast:
	$(MAKE) -f tests/unittest/elle/serialize/CMakeFiles/test_JSONArchive.dir/build.make tests/unittest/elle/serialize/CMakeFiles/test_JSONArchive.dir/build
.PHONY : test_JSONArchive/fast

#=============================================================================
# Target rules for targets named test_Pointer

# Build rule for target.
test_Pointer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Pointer
.PHONY : test_Pointer

# fast build rule for target.
test_Pointer/fast:
	$(MAKE) -f tests/unittest/elle/serialize/CMakeFiles/test_Pointer.dir/build.make tests/unittest/elle/serialize/CMakeFiles/test_Pointer.dir/build
.PHONY : test_Pointer/fast

#=============================================================================
# Target rules for targets named test_Serializable

# Build rule for target.
test_Serializable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Serializable
.PHONY : test_Serializable

# fast build rule for target.
test_Serializable/fast:
	$(MAKE) -f tests/unittest/elle/serialize/CMakeFiles/test_Serializable.dir/build.make tests/unittest/elle/serialize/CMakeFiles/test_Serializable.dir/build
.PHONY : test_Serializable/fast

#=============================================================================
# Target rules for targets named test_all_archives

# Build rule for target.
test_all_archives: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_all_archives
.PHONY : test_all_archives

# fast build rule for target.
test_all_archives/fast:
	$(MAKE) -f tests/unittest/elle/serialize/CMakeFiles/test_all_archives.dir/build.make tests/unittest/elle/serialize/CMakeFiles/test_all_archives.dir/build
.PHONY : test_all_archives/fast

#=============================================================================
# Target rules for targets named test_construct

# Build rule for target.
test_construct: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_construct
.PHONY : test_construct

# fast build rule for target.
test_construct/fast:
	$(MAKE) -f tests/unittest/elle/serialize/CMakeFiles/test_construct.dir/build.make tests/unittest/elle/serialize/CMakeFiles/test_construct.dir/build
.PHONY : test_construct/fast

#=============================================================================
# Target rules for targets named test_footprint

# Build rule for target.
test_footprint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_footprint
.PHONY : test_footprint

# fast build rule for target.
test_footprint/fast:
	$(MAKE) -f tests/unittest/elle/serialize/CMakeFiles/test_footprint.dir/build.make tests/unittest/elle/serialize/CMakeFiles/test_footprint.dir/build
.PHONY : test_footprint/fast

#=============================================================================
# Target rules for targets named test_version_change

# Build rule for target.
test_version_change: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_version_change
.PHONY : test_version_change

# fast build rule for target.
test_version_change/fast:
	$(MAKE) -f tests/unittest/elle/serialize/CMakeFiles/test_version_change.dir/build.make tests/unittest/elle/serialize/CMakeFiles/test_version_change.dir/build
.PHONY : test_version_change/fast

#=============================================================================
# Target rules for targets named test_Region

# Build rule for target.
test_Region: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Region
.PHONY : test_Region

# fast build rule for target.
test_Region/fast:
	$(MAKE) -f tests/unittest/elle/standalone/CMakeFiles/test_Region.dir/build.make tests/unittest/elle/standalone/CMakeFiles/test_Region.dir/build
.PHONY : test_Region/fast

#=============================================================================
# Target rules for targets named test_ImprintBlock

# Build rule for target.
test_ImprintBlock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ImprintBlock
.PHONY : test_ImprintBlock

# fast build rule for target.
test_ImprintBlock/fast:
	$(MAKE) -f tests/unittest/nucleus/proton/CMakeFiles/test_ImprintBlock.dir/build.make tests/unittest/nucleus/proton/CMakeFiles/test_ImprintBlock.dir/build
.PHONY : test_ImprintBlock/fast

#=============================================================================
# Target rules for targets named test_nn_Group

# Build rule for target.
test_nn_Group: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_nn_Group
.PHONY : test_nn_Group

# fast build rule for target.
test_nn_Group/fast:
	$(MAKE) -f tests/unittest/nucleus/neutron/CMakeFiles/test_nn_Group.dir/build.make tests/unittest/nucleus/neutron/CMakeFiles/test_nn_Group.dir/build
.PHONY : test_nn_Group/fast

#=============================================================================
# Target rules for targets named test_nn_Object

# Build rule for target.
test_nn_Object: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_nn_Object
.PHONY : test_nn_Object

# fast build rule for target.
test_nn_Object/fast:
	$(MAKE) -f tests/unittest/nucleus/neutron/CMakeFiles/test_nn_Object.dir/build.make tests/unittest/nucleus/neutron/CMakeFiles/test_nn_Object.dir/build
.PHONY : test_nn_Object/fast

#=============================================================================
# Target rules for targets named test_nn_Record

# Build rule for target.
test_nn_Record: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_nn_Record
.PHONY : test_nn_Record

# fast build rule for target.
test_nn_Record/fast:
	$(MAKE) -f tests/unittest/nucleus/neutron/CMakeFiles/test_nn_Record.dir/build.make tests/unittest/nucleus/neutron/CMakeFiles/test_nn_Record.dir/build
.PHONY : test_nn_Record/fast

#=============================================================================
# Target rules for targets named test_gap

# Build rule for target.
test_gap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_gap
.PHONY : test_gap

# fast build rule for target.
test_gap/fast:
	$(MAKE) -f tests/unittest/surface/gap/CMakeFiles/test_gap.dir/build.make tests/unittest/surface/gap/CMakeFiles/test_gap.dir/build
.PHONY : test_gap/fast

#=============================================================================
# Target rules for targets named test_rpc

# Build rule for target.
test_rpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_rpc
.PHONY : test_rpc

# fast build rule for target.
test_rpc/fast:
	$(MAKE) -f tests/unittest/protocol/CMakeFiles/test_rpc.dir/build.make tests/unittest/protocol/CMakeFiles/test_rpc.dir/build
.PHONY : test_rpc/fast

#=============================================================================
# Target rules for targets named gap

# Build rule for target.
gap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gap
.PHONY : gap

# fast build rule for target.
gap/fast:
	$(MAKE) -f surface/gap/CMakeFiles/gap.dir/build.make surface/gap/CMakeFiles/gap.dir/build
.PHONY : gap/fast

#=============================================================================
# Target rules for targets named _gap

# Build rule for target.
_gap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _gap
.PHONY : _gap

# fast build rule for target.
_gap/fast:
	$(MAKE) -f surface/gap/python/CMakeFiles/_gap.dir/build.make surface/gap/python/CMakeFiles/_gap.dir/build
.PHONY : _gap/fast

#=============================================================================
# Target rules for targets named _metalib

# Build rule for target.
_metalib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _metalib
.PHONY : _metalib

# fast build rule for target.
_metalib/fast:
	$(MAKE) -f oracle/disciples/metalib/CMakeFiles/_metalib.dir/build.make oracle/disciples/metalib/CMakeFiles/_metalib.dir/build
.PHONY : _metalib/fast

Infinit.o: Infinit.cc.o
.PHONY : Infinit.o

# target to build an object file
Infinit.cc.o:
	$(MAKE) -f CMakeFiles/infinit.dir/build.make CMakeFiles/infinit.dir/Infinit.cc.o
.PHONY : Infinit.cc.o

Infinit.i: Infinit.cc.i
.PHONY : Infinit.i

# target to preprocess a source file
Infinit.cc.i:
	$(MAKE) -f CMakeFiles/infinit.dir/build.make CMakeFiles/infinit.dir/Infinit.cc.i
.PHONY : Infinit.cc.i

Infinit.s: Infinit.cc.s
.PHONY : Infinit.s

# target to generate assembly for a file
Infinit.cc.s:
	$(MAKE) -f CMakeFiles/infinit.dir/build.make CMakeFiles/infinit.dir/Infinit.cc.s
.PHONY : Infinit.cc.s

_infinit.o: _infinit.cc.o
.PHONY : _infinit.o

# target to build an object file
_infinit.cc.o:
	$(MAKE) -f CMakeFiles/8infinit.dir/build.make CMakeFiles/8infinit.dir/_infinit.cc.o
.PHONY : _infinit.cc.o

_infinit.i: _infinit.cc.i
.PHONY : _infinit.i

# target to preprocess a source file
_infinit.cc.i:
	$(MAKE) -f CMakeFiles/8infinit.dir/build.make CMakeFiles/8infinit.dir/_infinit.cc.i
.PHONY : _infinit.cc.i

_infinit.s: _infinit.cc.s
.PHONY : _infinit.s

# target to generate assembly for a file
_infinit.cc.s:
	$(MAKE) -f CMakeFiles/8infinit.dir/build.make CMakeFiles/8infinit.dir/_infinit.cc.s
.PHONY : _infinit.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... 8infinit"
	@echo "... dependencies"
	@echo "... edit_cache"
	@echo "... infinit"
	@echo "... rebuild_cache"
	@echo "... comet"
	@echo "... elle"
	@echo "... common"
	@echo "... nucleus"
	@echo "... protocol"
	@echo "... etoile"
	@echo "... agent"
	@echo "... lune"
	@echo "... horizon"
	@echo "... macosx"
	@echo "... hole"
	@echo "... 8access"
	@echo "... 8authority"
	@echo "... 8dictionary"
	@echo "... 8group"
	@echo "... 8network"
	@echo "... 8passport"
	@echo "... 8setup"
	@echo "... 8user"
	@echo "... 8watchdog"
	@echo "... metal"
	@echo "... test"
	@echo "... test_testing_tests"
	@echo "... test_log"
	@echo "... test_print"
	@echo "... test_ec_PrivateKey"
	@echo "... test_ec_SecretKey"
	@echo "... test_ec_all"
	@echo "... test_Section"
	@echo "... test_Array"
	@echo "... test_Bool"
	@echo "... test_Dictionary"
	@echo "... test_Float"
	@echo "... test_Integer"
	@echo "... test_Null"
	@echo "... test_String"
	@echo "... test_Locus"
	@echo "... test_Path"
	@echo "... test_Base64Archive"
	@echo "... test_BinaryArchive"
	@echo "... test_BufferArchive"
	@echo "... test_JSONArchive"
	@echo "... test_Pointer"
	@echo "... test_Serializable"
	@echo "... test_all_archives"
	@echo "... test_construct"
	@echo "... test_footprint"
	@echo "... test_version_change"
	@echo "... test_Region"
	@echo "... test_ImprintBlock"
	@echo "... test_nn_Group"
	@echo "... test_nn_Object"
	@echo "... test_nn_Record"
	@echo "... test_gap"
	@echo "... test_rpc"
	@echo "... gap"
	@echo "... _gap"
	@echo "... _metalib"
	@echo "... Infinit.o"
	@echo "... Infinit.i"
	@echo "... Infinit.s"
	@echo "... _infinit.o"
	@echo "... _infinit.i"
	@echo "... _infinit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

