#!/bin/sh

ROOT=$(realpath $(dirname "$0"))

error ()
{
    for line; do
        echo 1>&2 "$line"
    done
    exit 1
}

run ()
{
    echo "Running: $@"
    "$@"
}


case "$1" in
    (-f)
        CONFIRM=y
        ;;
    (*)
        echo -n "Reset networks in $ROOT/configuration/ (y/n) ? "
        read CONFIRM
        ;;
esac

case "$CONFIRM" in
    (y*|Y*)
        ;;
    (*)
        error "Aborted"
        ;;
esac

cd "$ROOT"
run git checkout HEAD "$ROOT/configuration/"
for network in "$ROOT"/configuration/networks/*; do
    run git clean -fd $network/shelter
done
