#!/usr/bin/env python3

import os
import os.path
import subprocess
import sys

arch, osyst, compiler = os.environ['BUILDFARM_NAME'].split('-')

cwd = os.getcwd()
dir_build, dir_install, dir_source = (
  os.environ['DIR_%s' % name] for name in ('BUILD', 'INSTALL', 'SOURCE'))

os.chdir('%s' % os.environ['DIR_BUILD'])
jobs = '2' if osyst == 'osx' else os.environ['JOBS']
if subprocess.call(['python3', 'drake', '-j', jobs, '//build']) != 0:
  exit(1)
