#!/usr/bin/env python3
# -*- python -*-

import drake
import drake.cxx
import drake.cxx.boost

def test(path, expect = True):
  if expect:
    drake.cxx.boost.Boost(prefix = path)
  else:
    try:
      drake.cxx.boost.Boost(prefix = path)
    except:
      pass
    else:
      raise Exception('Boost shall not be found in %s' % path)

# Simplest case
test('deps/simplest')
# Inexistent directory
test('deps/inexistent', False)
# Missing boost include dir
test('deps/no-include', False)
# Invalid version file
test('deps/no-version', False)
# Include files in a boost-$version subdirectory.
test('deps/include-version')
