#!/usr/bin/env python3

import os
import drake
import drake.cxx
import drake.cxx.boost

cxx_compiler = os.getenv('CXX', 'g++')

cxx_toolkit = drake.cxx.GccToolkit(compiler = cxx_compiler)
cxx_config = drake.cxx.Config()
cxx_config.flag('-fPIC')
cxx_config.flag('-Wall')
cxx_config.enable_debug_symbols(False)
cxx_config.enable_optimization(True)
cxx_config.add_system_include_path('.')

openssl = drake.cxx.LibraryConfiguration(
  'openssl/opensslconf.h',
  prefix = '/opt/local',
)

boost = drake.cxx.boost.Boost(prefix = '/opt/local')

elle = drake.include('../../../elle',
                     cxx_toolkit = cxx_toolkit,
                     cxx_config = cxx_config,
                     boost = boost,
                     curl = None)

drake.run(
    '../..',
    cxx_toolkit,
    cxx_config,
    openssl = openssl.config(),
    boost = boost,
    elle = elle,
)
