#!/bin/sh

if test -z "$NO_COLORS"; then
    red="[33;01;31m"
    green="[33;01;32m"
    blue="[33;01;36m"
    yellow="[33;01;33m"
    purple="[33;01;34m"
    lred="[33;00;31m"
    lgreen="[33;00;32m"
    lblue="[33;00;36m"
    lyellow="[33;00;33m"
    lpurple="[33;00;34m"
    tst="[33;00;35m"
    white="[0m"
fi

SELF="$0"
ROOT="$(dirname $0)"
export PYTHONPATH="$PWD/$ROOT/../src:$PYTHONPATH"

for test in $(find * -name 'drake-build.py' -not -path '*/.test/*' | sort); do
    (
        dir="$(dirname "$test")/.test"
        rm -rf "$dir"
        mkdir "$dir"
        cp -r "$(dirname "$test")"/* $dir
        cd "$dir"
        echo "===== $test =====" >> log
        echo >> log

        res=true
        for i in $(seq $(test -r iter && cat iter || echo 1)); do
            ./drake-build.py $i > out.log.$i 2> err.log.$i
            rv=$?
            echo $rv > rv.log.$i
            {
                echo "Run $i: $rv"
                if test $(wc -l < out.log.$i) -gt 0; then
                    echo "=== stdout ==="
                    sed 's/^/  /' out.log.$i
                    echo "=============="
                fi
                if test $(wc -l < err.log.$i) -gt 0; then
                    echo "=== stderr ==="
                    sed 's/^/  /' err.log.$i
                    echo "=============="
                fi

            } >> log
            test $rv -eq 0 || res=false
        done
        if $res; then
            status="${green}PASS${white}: "
        else
            status="${red}FAIL${white}: "
        fi
        echo "${status}${purple}$(dirname "$test")/.test/log${white}"
    )
done
