#!/usr/bin/env python
# -*- encoding: utf-8 -*-

import troll
import pythia

from creosus import pages

views = {
    '': pages.Root,
    'register': pages.Register,
    'login': pages.Login,
}

conf = {
    'database': None,
    'template_dir': 'creosus/templates',
    'meta_server': pythia.constants.DEFAULT_SERVER,
    'fastcgi': True,
}

if __name__ == '__main__':
    app = troll.Application(views, conf=conf)
    app.run()
