#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from creosus import pages

import troll

views = {
    '': pages.Root,
    'register': pages.Register,
}

conf = {
    'database': None,
}

if __name__ == '__main__':
    app = troll.Application(views, conf=conf)
    app.run()
