#!/usr/bin/env python

#
# ---------- imports ----------------------------------------------------------
#

import sys

from meta.application import Application

#
# ---------- functions --------------------------------------------------------
#

def Usage():
  print 'usage: $> ' + sys.argv[0]
  sys.exit(1)

#
# ---------- main -------------------------------------------------------------
#

if __name__ == '__main__':
  if len(sys.argv) != 1:
    Usage()

  app = Application("0.0.0.0")
  app.run()
