#!/usr/bin/env python3
# -*- python -*-

import drake, drake.cxx, drake.cxx.qt, subprocess, sys

with drake.Drake('.') as d:
  sys.argv = ['main']
  qt = drake.cxx.qt.Qt()
  d.run(cxx_toolkit = drake.cxx.Toolkit(), qt = qt)

with drake.Drake('.') as d:
  sys.argv = ['main']
  qt = drake.cxx.qt.Qt()
  d.run(cxx_toolkit = drake.cxx.Toolkit(), qt = qt)
