#ifndef ETOILE_PORTAL_PORTAL_HH
# define ETOILE_PORTAL_PORTAL_HH

# include <elle/types.hh>

# include <reactor/fwd.hh>
# include <reactor/network/fwd.hh>

# include <etoile/portal/Application.hh>

# include <lune/Phrase.hh>

# include <elle/idiom/Close.hh>
#  include <map>
# include <elle/idiom/Open.hh>

namespace etoile
{
  ///
  /// this namespace contains everything related to making the Etoile's
  /// interface accessible through messaging.
  ///
  /// note that in order to be used, the client application must provide
  /// a phrase which is generated by the user's instance of Infinit.
  ///
  namespace portal
  {

    ///
    /// this class is responsible for managing the external applications
    /// connecting to Etoile and triggering operations.
    ///
    class Portal
    {
      /*----------.
      | Constants |
      `----------*/
    public:
      static elle::Natural32 const pass_length = 128;

    public:
      //
      // types
      //
      typedef std::pair<reactor::network::TCPSocket*, Application*>       Value;
      typedef std::map<reactor::network::TCPSocket*, Application*>        Container;
      typedef Container::iterator                               Iterator;
      typedef Container::const_iterator                         Scoutor;

      //
      // static methods
      //
      static elle::Status       Initialize();
      static elle::Status       Clean();

      static elle::Status       Add(Application*);
      static elle::Status       Retrieve(reactor::network::TCPSocket*,
                                         Application*&);
      static elle::Status       Remove(reactor::network::TCPSocket*);

      static elle::Status       Show(const elle::Natural32 = 0);

      static void accept();

      //
      // static callbacks
      //
      static elle::Status       Connection(reactor::network::TCPSocket*);
      static elle::Status       Authenticate(const elle::String&);

      //
      // static attributes
      //
      static Container applications;
      static reactor::network::TCPServer* server;
      static reactor::Thread* acceptor;
      static lune::Phrase phrase;
    };

  }
}

#endif
