#!/usr/bin/env python3

import drake, drake.sched
import traceback

class Beacon(Exception):
  pass

# Sub no exceptions

beacon_main_1 = False
beacon_main_2 = False
beacon_sub_1 = False
beacon_sub_2 = False

SCHED = drake.sched.Scheduler()

def main():
  global beacon_main_1, beacon_main_2
  beacon_main_1 = True
  sub()
  beacon_main_2 = True

def sub():
  global beacon_sub_1, beacon_sub_2
  beacon_sub_1 = True
  drake.sched.coro_yield()
  beacon_sub_2 = True

drake.sched.Coroutine(main, "main", SCHED)
SCHED.run()
assert beacon_main_1
assert beacon_main_2
assert beacon_sub_1
assert beacon_sub_2

# Sub exception

beacon_main_1 = False
beacon_main_2 = False
beacon_sub_1 = False
beacon_sub_2 = False

def main():
  global beacon_main_1, beacon_main_2
  try:
    beacon_main_1 = True
    sub()
    assert False
  finally:
    beacon_main_2 = True

def sub():
  global beacon_sub_1, beacon_sub_2
  beacon_sub_1 = True
  drake.sched.coro_yield()
  beacon_sub_2 = True
  raise Beacon("test.")
  drake.sched.coro_yield()
  assert False

drake.sched.Coroutine(main, "main", SCHED)
try:
  SCHED.run()
except Beacon:
  pass
else:
  assert False

assert beacon_main_1
assert beacon_main_2
assert beacon_sub_1
assert beacon_sub_2


# Join no exception

beacon_main_1 = False
beacon_main_2 = False
beacon_sub_1 = False
beacon_sub_2 = False

def main():
  global beacon_main_1, beacon_main_2
  beacon_main_1 = True
  sub()
  beacon_main_2 = True

def sub():
  global beacon_sub_1, beacon_sub_2
  beacon_sub_1 = True
  drake.sched.coro_yield()
  beacon_sub_2 = True
  assert not beacon_main_2

drake.sched.Coroutine(main, "main", SCHED)
SCHED.run()

assert beacon_main_1
assert beacon_main_2
assert beacon_sub_1
assert beacon_sub_2


# Join exception

beacon_main_1 = False
beacon_main_2 = False
beacon_sub_1 = False
beacon_sub_2 = False

def main():
  global beacon_main_1, beacon_main_2
  try:
    beacon_main_1 = True
    c = drake.sched.Coroutine(sub, "sub", SCHED,
                              parent = drake.sched.Coroutine.current)
    drake.sched.coro_wait(c)
    assert False
  finally:
    beacon_main_2 = True

def sub():
  global beacon_sub_1, beacon_sub_2
  beacon_sub_1 = True
  drake.sched.coro_yield()
  beacon_sub_2 = True
  assert not beacon_main_2
  raise Beacon("test.")

drake.sched.Coroutine(main, "main", SCHED)
try:
  SCHED.run()
except Beacon:
  pass
else:
  assert False

assert beacon_main_1
assert beacon_main_2
assert beacon_sub_1
assert beacon_sub_2
