#!/usr/bin/env python3
# -*- python -*-

import drake
import os
import sys

with drake.Drake('.') as d:
  sys.argv = ['main']
  d.run()

with drake.Drake('.') as d:
  sys.argv = ['main']
  d.run()

os.remove('main')
with drake.Drake('.') as d:
  sys.argv = ['main']
  d.run()
