#!/usr/bin/env python3

import os
import sys

# Add drake to the Python path.
# You could also use your PYTHONPATH to specify where drake is.
sys.path.insert(0, os.path.realpath('../../../../src'))

import drake
import drake.cxx

# Set the C++ compiler to be clang++ and the C compiler to be clang.
cxx_toolkit = drake.cxx.GccToolkit(compiler = 'clang++', compiler_c = 'clang')
# Use a default C++ compiler configuration.
cxx_config = drake.cxx.Config()

# Specify that clang++ should use libc++.
cxx_config.flag('-stdlib=libc++')

# Instantiate drake to look for a drakefile at '../../drakefile'.
# Pass the specified toolkit and compiler configuration.
with drake.Drake('../..') as d:
  d.run(cxx_toolkit = cxx_toolkit,
        cxx_config = cxx_config)
