#!/usr/bin/env python3

import os, sys
sys.path.insert(
    0,
    os.path.abspath(
        os.path.join(os.path.dirname(__file__), '../../drake/src')
    )
)

import drake
import drake.valgrind

with drake.Drake('../..') as d:
  d.run(valgrind = drake.valgrind.Valgrind())
