#!/usr/bin/env python3

import os, sys
sys.path.insert(
    0,
    os.path.abspath(
        os.path.join(os.path.dirname(__file__), '../../drake/src')
    )
)

import drake
import drake.cxx
import drake.valgrind

try:
  valgrind = drake.valgrind.Valgrind()
except:
  valgrind = None

with drake.Drake('../..') as d:
  python3 = drake.cxx.find_library(
    token = 'pyconfig.h',
    include_dir = 'include/python3.5m')
  d.run(python3 = python3,
        valgrind = valgrind)
