ROOTDIR="/Users/mycure/infinit/dependencies"
PLATFORM="macosx64"
PLATFORMDIR="/Users/mycure/infinit/dependencies/platforms/macosx64"
BUILDDIR="/Users/mycure/infinit/dependencies/build"
WORKDIR="/Users/mycure/infinit/dependencies/work"
