#!/usr/bin/env zsh

infinitd_probe() {
	for proc in $(pgrep 8watchdog)
	do
		i8info 8watchdog \(pid ${proc}\)
		for child in $(ps h -o pid --ppid ${proc})
		do
			i8info " " 8infinit \(pid ${child}\)
		done
	done
}

infinitd_stop() {
	for proc in $(pgrep 8watchdog)
	do
		for child in $(ps h -o pid --ppid ${proc})
		do
			i8warn Stopping 8infinit \(with pid ${child}\)
			kill -9 $child
		done
		i8warn Stopping 8watchdog \(with pid ${proc}\)
		kill -9 $proc
	done
}
