#!/usr/bin/env sh

source ${INFINIT_SOURCE_DIR}/scripts/common.sh

infinit_clean() {
    for mountpoint in $(sudo mount -t fuse.infinit | cut -d " " -f 3)
    do
        i8info unmount $mountpoint
        fusermount -u $mountpoint
    done
}

infinit_clean
