#!/usr/bin/env python3
# -*- python -*-

import os
import subprocess
import sys

os.environ['PYTHONDONTWRITEBYTECODE'] = '1'

import drake
import drake.cxx

with open('utils.py', 'w') as f:
  print('value = 42', file = f)

# Run the test and check output
with drake.Drake():
  drake.run('.')
  with open('main.py.out', 'r') as f:
    assert f.read() == '42\n'

# Check it's not re-run
with drake.Drake():
  with open('main.py.out', 'w') as f:
    print('43', file = f)
  drake.run('.')
  with open('main.py.out', 'r') as f:
    assert f.read() == '43\n'

# Check it's re-run after changing a dependency
with drake.Drake():
  with open('utils.py', 'w') as f:
    print('value = 51', file = f)
  drake.run('.')
  with open('main.py.out', 'r') as f:
    assert f.read() == '51\n'
