#!/usr/bin/env python3

'''Check the build chain stops when a builder fails.'''

import drake
import utils
import sys


def bool_cli(foo: bool):
  assert foo is False

with utils.Drake() as d:
  d.configure = bool_cli
  sys.argv.append('--foo=false')
  d.run()
  del sys.argv[-1]

def positional(a = 0, b = 1):
  assert a == b

with utils.Drake() as d:
  d.configure = positional
  d.run(a = 1)

with utils.Drake() as d:
  d.configure = positional
  d.run(1)
