#!/usr/bin/env python3
# -*- python -*-

import drake
import os
import stat
import tempfile

from utils import *

os.environ['PYTHONDONTWRITEBYTECODE'] = '1'

def drakefile():
  exe = drake.node('main.py')
  exe.dependency_add(drake.node('utils.py'))
  runner = drake.Runner(exe)
  return drake.node('main.py.out')

with tempfile.TemporaryDirectory() as wd:

  os.chdir(wd)
  with open('utils.py', 'w') as f:
    print('value = 42', file = f)
  with open('main.py', 'w') as f:
    print('''#!/usr/bin/env python3

import utils

print(utils.value)
''', file = f)
  os.chmod('main.py', stat.S_IRUSR | stat.S_IXUSR)

  # Run the test and check output
  with Drake(wd):
    drakefile().build()
    with open('main.py.out', 'r') as f:
      assertEq(f.read(), '42\n')

  with open('main.py.out', 'w') as f:
    print('43', file = f)

  # Check it's not re-run
  with Drake(wd):
    drakefile().build()
    with open('main.py.out', 'r') as f:
      assertEq(f.read(), '43\n')

  with open('utils.py', 'w') as f:
    print('value = 51', file = f)

  # Check it's re-run after changing a dependency
  with Drake(wd):
    drakefile().build()
    with open('main.py.out', 'r') as f:
      assert f.read() == '51\n'
