#!/usr/bin/env python3

'''Check an interrupted build is not considered to have run
successfully later.'''

import drake
import drake.sched

from utils import *

class FailBuilder(drake.Builder):

  def execute(self):
    self._run_job(lambda: False)

beacon = False
class SuccessBuilder(TouchBuilder):

  def execute(self):
    global beacon
    try:
      if self._run_job(lambda: TouchBuilder.execute(self)):
        beacon = True
        return True
    except:
      print('bye')
      raise

with Drake(jobs = 2) as d:
  failed = drake.node('failed')
  failer = FailBuilder([], [failed])
  built  = drake.node('built')
  builder = SuccessBuilder([], [built])
  root = drake.node('root')
  TouchBuilder([failed, built], [root])
  try:
    root.build()
  except drake.Builder.Failed as e:
    assert e.builder is failer
    assert os.path.exists('built')
    assert beacon
  else:
    raise Exception('build should have failed')
